sonar.projectKey=michaeltg17_Angular
sonar.organization=michaeltg17
sonar.sources=src/
sonar.language=ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=**/*.spec.ts,**/node_modules/**,**/dist/**,**/coverage/**,**/playwright/**