name: cd

on:
  workflow_run:
    workflows:
      - "ci"
    types:
      - completed
    branches: [main]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag'
        required: true
        default: 'latest'

jobs:
  deploy-dev:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: https://dev.shop.statikk.mooo.com
    steps:
      - uses: ./.github/actions/deploy
        with:
          environment: dev
          tag: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.tag || github.event.workflow_run.head_sha }}
          deploy_user: ${{ secrets.DEPLOY_USER }}
          deploy_password: ${{ secrets.DEPLOY_PASSWORD }}

  deploy-qa:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    needs: deploy-dev
    runs-on: ubuntu-latest
    environment:
      name: qa
      url: https://qa.shop.statikk.mooo.com
    steps:
      - uses: ./.github/actions/deploy
        with:
          environment: qa
          tag: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.tag || github.event.workflow_run.head_sha }}
          deploy_user: ${{ secrets.DEPLOY_USER }}
          deploy_password: ${{ secrets.DEPLOY_PASSWORD }}

  deploy-prod:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    needs: deploy-qa
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: https://shop.statikk.mooo.com
    steps:
      - uses: ./.github/actions/deploy
        with:
          environment: prod
          tag: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.tag || github.event.workflow_run.head_sha }}
          deploy_user: ${{ secrets.DEPLOY_USER }}
          deploy_password: ${{ secrets.DEPLOY_PASSWORD }}
