name: cd

on:
  workflow_run:
    workflows:
      - "ci"
    types:
      - completed
    branches: [main]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag'
        required: false
        default: 'latest'

if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
env:
  TAG: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.tag || github.event.workflow_run.head_sha }}

jobs:
  deploy-dev:
    environment:
      name: dev
      url: https://dev.shop.statikk.mooo.com
    uses: ./.github/workflows/deploy.yml
    with:
      environment: dev
      tag: ${{ env.TAG }}
    secrets: inherit

  deploy-qa:
    needs: deploy-dev
    environment:
      name: qa
      url: https://qa.shop.statikk.mooo.com
    uses: ./.github/workflows/deploy.yml
    with:
      environment: qa
      tag: ${{ env.TAG }}
    secrets: inherit

  deploy-prod:
    needs: deploy-qa
    environment:
      name: prod
      url: https://shop.statikk.mooo.com
    uses: ./.github/workflows/deploy.yml
    with:
      environment: prod
      tag: ${{ env.TAG }}
    secrets: inherit
